### ISSUE TITLE
Add case-insensitive assertion

### ISSUE THREAD

**Issue by asimell** [MarketSquare/AssertionEngine#124]
Recreated issue from [Browser#2951](https://github.com/MarketSquare/robotframework-browser/issues/2951).

Currently there's no direct way of doing a case-insensitive assertion and you need to do something like `Get Text    .my-element    validate    value.lower() == "some text"`.

Instead of "having" to use `validate` there could be a case-insensitive assertion something like

```
Get Text    .my-element   should be case-insensitive   some text    # option 1
Get Text    .my-element    ==!    some text    # option 2
```

There's the [formatters for assertion](https://marketsquare.github.io/robotframework-browser/Browser.html#Assertions), so this could probably be implemented as a formatter instead of a separate assertion as well.

**Comment by aaltat** [comment]
AssertionEngine 1.1.0 is out and implements case intensive as formatter.
