### ISSUE TITLE
Small request: "equals"

### ISSUE THREAD

**Issue by sd-yazzoom** [MarketSquare/AssertionEngine#136]
Would it be possible to add 'equals' to the list of possible operators?

${var}  equals  5

feels more natural than
${var}  equal  5

**Comment by aaltat** [comment]
That is good idea, we can keep both operators.

**Comment by aaltat** [comment]
Done and pushed release out. Should be backwards compatible, so example if you are using https://github.com/MarketSquare/robotframework-browser library, then updating assertion engine should be enough.
