### ISSUE TITLE
assertionEngine can't be used with robotframework 4.0

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/AssertionEngine#21]
When upgrading robotframework 3.2.2 to 4.0 a message is displayed preventing the upgrade.

"robotframework-assertion-engine 0.0.4 requires robotframework(4.0.0,>=3.2.2, but you have robotframework 4.0 which is incompatible)" 

I guess pip is not liking 4.0.0 instead of 4.0

**Comment by aaltat** [comment]
This is already fixed in master, but is not yet released. When I get back home, I will push release out.

**Comment by aaltat** [comment]
Well, publishing new release did took few days, but now 0.0.5 is out.
