### ISSUE TITLE
Issue from Browser: Assertion should fail if expected value is given without operator

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/AssertionEngine#27]
"Would definitely be better if there was a failure if assertion_expected is not None and assertion_operator is None.

Example in the keyword documentation would obviously help with correct usage as well."

https://github.com/MarketSquare/robotframework-browser/issues/1142

**Comment by aaltat** [comment]
I agree, should not be difficult to fix, somewhere [here](https://github.com/MarketSquare/AssertionEngine/blob/master/assertionengine/assertion_engine.py#L132). Something like:
```
if operator is None and expected:
    raise ValueError("Assertion can not be made with only expected value")
````
